name: ai_chat_bot_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.2
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  url_launcher: ^6.3.2
  firebase_core: ^4.0.0
  firebase_analytics: ^12.0.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.otf
        - asset: assets/fonts/Roboto-Regular.otf
        - asset: assets/fonts/Roboto-Medium.otf
        - asset: assets/fonts/Roboto-Bold.otf
        - asset: assets/fonts/Roboto-ExtraBold.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700